### ISSUE TITLE
Supported Platforms?

### ISSUE THREAD

**Issue by seandenigris** [magritte-metamodel/magritte#144]
Our Metacello Baseline is fairly complex. How far back are we committed to supporting? I'm making some Pharo 9 fixes and it would be great to simplify. @noha?

**Comment by noha** [comment]
I think 3-5 years makes sense. For pharo this would be pharo6 latest. Do you have changes to commit? Otherwise I‘ll preparr something for pharo9

**Comment by dalehenrich** [comment]
What are your thoughts on porting to GemStone? 

@dariogithub is interested in using Magritte with GemStone 3.5.3 so today I blew the dust off of  GsDevKit/Magritte3 and sure enough it is [passing the travis tests](https://travis-ci.org/github/GsDevKit/Magritte3/builds/729160775), but I am concerned that there are new features that are supported by GsDevKit/Magritte3, as it has been updated in 4-5 years ... 

I see that you've got a tonel port ongoing and GemStone won't support tonel until next year at the earliest so that could be a factor as well ...

**Comment by seandenigris** [comment]
GemStone support would be great. It seems like an important platform given the "write in Pharo, deploy to Gemstone" workflow. It may already (mostly?) work in Gemstone/Squeak - I guess it used to - but I just haven't tested it. The key question is who will port it and who will maintain it. @noha and I both seem to work exclusively in Pharo, and I don't usually have other images/platforms handy. Also, it has been unclear whether there was any interest, specifically from Squeakers.

**Comment by dalehenrich** [comment]
I would do the port ... the timing would depend upon @dariogithub ... if GsDevKit/Magritte3 meets his needs there is no immediate need to do the port ... with tonel packages in the wings and the addition of FileSystem packages (haven't looked at details), it may make sense to wait for 3.7 and Rowan, since we will finally have native tonel support and native FileSystem in 3.7 ...

**Comment by seandenigris** [comment]
Since we have someone responsible for the port, why not!? We should make sure to include GS in the CI to make sure we don’t break it since we’re working mostly in Pharo; @dalehenrich is GS compatible with SmalltalkCI?

**Comment by noha** [comment]
I would like to see gemstone in the list of users. Adding travis support for it is no question I guess. If it takes some time travis can have "allowed to fail" which builds it but does not break the whole build status if gemstone is not up-to-date. 
Regarding tonel: We really need it because there are other tools using magritte on thus failing for windows users because of the filename length issue. But @seandenigris what is the status for tonel? I switched my laptop to case-sensitive fielsystem and since then it seems to be impossible for me to switch to tonel because methods are vanishing. Can we join forces here. @dalehenrich We can make a release tag before the move to tonel and then move. As pharo9 is in the dependencies it should give you enought time to catch up with tonel. Ok?

**Comment by dariogithub** [comment]
Next week i should be able to check Magritte's status in Gemstone 353- 354. I'll update you soon. Thanks

**Comment by seandenigris** [comment]
Great! What versions of Gemstone cover the last two years? I'm happy to add them to the CI, but we'd need some commitment from someone to maintain them because if I break them I will not have the time or the knowledge to fix them.

**Comment by dalehenrich** [comment]
@dariogithub what is you status with Magritte and GemStone? I'm assuming that [GsDevKit/Magritte3](https://github.com/GsDevKit/Magritte3) is fulfilling your needs, since we haven't heard from you and the [GsDevKit/Magritte3 travis builds have been running green](https://travis-ci.org/github/GsDevKit/Magritte3). 

If that is true, then it falls back into my court to do the port to GemStone ... according to my schedule ... my plans would be to finish Rowan (yeah it is still not quite ready) and then do the port, as Rowan supports tonel format ... 

Once Rowan is included in the GemStone base product, I will be making a pass through the entire GLASS/GsDevKit ecosystem adding Rowan support and porting many of the projects to base GemStone (without requiring  GLASS ... GLASS would still be supported, just not required)

**Comment by dariogithub** [comment]
Into Gemstone 354 i load:

project install --url=http://gsdevkit.github.io/GsDevKit_home/Magritte3.ston

It report the git commit repository at: Master f856572

From it i load these package:

- Magritte-GemStone-Model (Magritte-GemStone-Model-dkh.8)
- Magritte-GemStone-Seaside (Magritte-GemStone-Seaside-DaleHenrichs.2)
- Magritte-Model (Magritte-Model-dkh.463)
- Magritte-Seaside (Magritte-Seaside-EstebanMaringolo.359)

At this point the:  http://localhost:1750/magritte/editor
seems to work right.

However, I didn't have time to install what I developed based on Magritte which would confirm everything.
I hope to check everything soon ...

**Comment by seandenigris** [comment]
From aa1ccd7:
- Fixes (as far as Pharo) magritte-metamodel#144, but still waiting on Gemstone...
- We will only support Pharo 6+

Close for now as haven't heard back re gemstone
