### ISSUE TITLE
MASelectorAccessor does not work for more complex selectors

### ISSUE THREAD

**Issue by pavel-krivanek** [magritte-metamodel/magritte#197]
The metadescription of MASelectorAccessor enables only simple accessors that have write selector derived from the read selector. Maybe it would make sense to introduce another MAAccessor for them rather than use MASelectorAccessor for both cases.

```smalltalk
aDescription := MASelectorAccessor read: #children write: #setChildren:.
p := aDescription asMASpPresenterIn: SpApplication new.
p openModalWithSpec.
```

![Pharo_bJFcBeXtYn](https://user-images.githubusercontent.com/572494/111964987-818c2c80-8af5-11eb-9bb6-f47c84aad57e.png)

(example requires Magritte-Spec)

**Comment by seandenigris** [comment]
How important is this to you? I'm hesitant to make the core model more complex for what seems like an edge case. The real problem is that the forms are "dumb" in the sense that they can't handle relationships/invariants between fields. It's something that I've wanted to address for a long time but haven't gotten around to yet...

**Comment by pavel-krivanek** [comment]
I'm trying to use Magritte to allow other developers and power-users to define their complex models using Spec UI and cases like this are breaking it. Magritte should really be well described by itself. In this particualr case, we should simply split it to `readSelector` and `writeSelector`.

It there are mechanisms missing for proper description of Magritte itself, it is clear that users will face soon the same limitations.
